# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, verbose_name='Keterangan Tambahan')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Waktu diedit')),
                ('status', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_delete', models.BooleanField(default=False, verbose_name='Soft Delete')),
                ('name', models.CharField(max_length=30)),
                ('driver', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Customers',
            },
        ),
    ]
