# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-16 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
