# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-16 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20170116_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=vehicles.models.upload_location, width_field='width_field'),
        ),
    ]
